import { Link } from 'react-router-dom'
import {
  CheckCircle2, MapPin, Upload, LogIn, FileText,
  AlertTriangle, Clock, TrendingDown, AlertCircle,
  Plus, UserPlus, BarChart2,
  ClipboardList,
} from 'lucide-react'

const activities = [
  { icon: CheckCircle2, color: '#10B981', bg: '#ECFDF5', text: 'Survey #3 completed by Rajesh Kumar', time: '2 min ago' },
  { icon: MapPin,       color: '#5B5CEB', bg: '#EEF2FF', text: 'Booth 42 – Rishikesh assigned to Phase 2', time: '18 min ago' },
  { icon: Upload,       color: '#F59E0B', bg: '#FFFBEB', text: 'CSV import of 5,240 voters completed', time: '1 hr ago' },
  { icon: LogIn,        color: '#06B6D4', bg: '#ECFEFF', text: 'Agent Priya Sharma logged in from Haridwar', time: '2 hr ago' },
  { icon: FileText,     color: '#8B5CF6', bg: '#F5F3FF', text: 'Phase 2 report generated by Admin', time: '3 hr ago' },
]

const notifications = [
  { icon: AlertTriangle, color: '#EF4444', bg: '#FEF2F2', text: 'Booth 112 inactive for 3 days', tag: 'Critical' },
  { icon: Clock,         color: '#F59E0B', bg: '#FFFBEB', text: 'Survey #2 deadline in 2 days',  tag: 'Warning' },
  { icon: TrendingDown,  color: '#8B5CF6', bg: '#F5F3FF', text: 'Low response rate — Chamoli zone', tag: 'Info' },
  { icon: AlertCircle,   color: '#06B6D4', bg: '#ECFEFF', text: 'Duplicate import detected (42 rows)', tag: 'Notice' },
]

const pendingWork = [
  { label: 'Pending Surveys',        value: 2,  color: '#5B5CEB', bg: '#EEF2FF' },
  { label: 'Booths without Activity', value: 12, color: '#EF4444', bg: '#FEF2F2' },
  { label: 'Unassigned Booths',       value: 8,  color: '#F59E0B', bg: '#FFFBEB' },
  { label: 'Inactive Agents',         value: 16, color: '#8B5CF6', bg: '#F5F3FF' },
]

const quickActions = [
  { icon: ClipboardList, label: 'Create Survey',   link: '/surveys',      color: '#5B5CEB', bg: '#EEF2FF' },
  { icon: Upload,        label: 'Import Voters',   link: '/voters',       color: '#10B981', bg: '#ECFDF5' },
  { icon: MapPin,        label: 'Add Booth',        link: '/booths',       color: '#F59E0B', bg: '#FFFBEB' },
  { icon: UserPlus,      label: 'Add Agent',        link: '/booth-agents', color: '#EC4899', bg: '#FDF2F8' },
  { icon: BarChart2,     label: 'Generate Report',  link: '/reports',      color: '#8B5CF6', bg: '#F5F3FF' },
]

function Card({ title, children, className = '' }) {
  return (
    <div className={`bg-white rounded-2xl border border-[#E8ECF4] p-5 ${className}`} style={{ boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
      {title && <h3 className="text-slate-800 font-semibold text-[13px] mb-4">{title}</h3>}
      {children}
    </div>
  )
}

function RecentActivity() {
  return (
    <Card title="Recent Activity">
      <div className="space-y-0">
        {activities.map((a, i) => {
          const Icon = a.icon
          return (
            <div key={i} className="flex gap-3 pb-4 relative">
              {i < activities.length - 1 && (
                <div className="absolute left-4 top-8 bottom-0 w-px bg-slate-100" />
              )}
              <div className="w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center z-10" style={{ background: a.bg }}>
                <Icon size={14} style={{ color: a.color }} />
              </div>
              <div className="flex-1 min-w-0 pt-0.5">
                <p className="text-slate-700 text-[12px] leading-relaxed">{a.text}</p>
                <p className="text-slate-400 text-[11px] mt-0.5">{a.time}</p>
              </div>
            </div>
          )
        })}
      </div>
    </Card>
  )
}

function PhaseSummary() {
  const pct = 62
  return (
    <Card title="Phase Summary">
      <div className="space-y-3 mb-4">
        {[
          ['Phase', 'Phase 2'],
          ['Start Date', '01 May 2024'],
          ['End Date', '31 May 2024'],
          ['Days Left', '6 days'],
          ['Total Booths', '300'],
          ['Covered Booths', '142'],
          ['Remaining Booths', '158'],
        ].map(([k, v]) => (
          <div key={k} className="flex items-center justify-between py-1.5 border-b border-slate-50 last:border-0">
            <span className="text-slate-400 text-[12px]">{k}</span>
            <span className="text-slate-700 text-[12px] font-semibold">{v}</span>
          </div>
        ))}
      </div>
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <span className="text-slate-500 text-[11px]">Completion</span>
          <span className="font-bold text-[13px]" style={{ color: '#5B5CEB' }}>{pct}%</span>
        </div>
        <div className="h-2.5 rounded-full overflow-hidden" style={{ background: '#F1F5F9' }}>
          <div className="h-full rounded-full" style={{ width: `${pct}%`, background: 'linear-gradient(90deg, #5B5CEB, #818CF8)' }} />
        </div>
      </div>
    </Card>
  )
}

function PendingWork() {
  return (
    <Card title="Pending Work">
      <div className="space-y-3">
        {pendingWork.map(({ label, value, color, bg }) => (
          <div key={label} className="flex items-center justify-between p-3 rounded-xl border border-slate-100" style={{ background: bg + '60' }}>
            <span className="text-slate-600 text-[12px] font-medium">{label}</span>
            <span className="text-lg font-bold" style={{ color }}>{value}</span>
          </div>
        ))}
      </div>
    </Card>
  )
}

function Notifications() {
  const tagColors = { Critical: '#EF4444', Warning: '#F59E0B', Info: '#8B5CF6', Notice: '#06B6D4' }
  return (
    <Card title="Notifications">
      <div className="space-y-3">
        {notifications.map((n, i) => {
          const Icon = n.icon
          return (
            <div key={i} className="flex gap-3 p-3 rounded-xl border border-slate-100 hover:border-slate-200 transition-colors">
              <div className="w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center" style={{ background: n.bg }}>
                <Icon size={14} style={{ color: n.color }} />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-slate-700 text-[12px] leading-snug">{n.text}</p>
                <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded-full mt-1 inline-block"
                  style={{ color: tagColors[n.tag], background: n.bg }}>
                  {n.tag}
                </span>
              </div>
            </div>
          )
        })}
      </div>
    </Card>
  )
}

function QuickActions() {
  return (
    <Card title="Quick Actions">
      <div className="space-y-2">
        {quickActions.map(({ icon: Icon, label, link, color, bg }) => (
          <Link
            key={label}
            to={link}
            className="flex items-center gap-3 p-3 rounded-xl border border-slate-100 hover:border-slate-200 hover:shadow-sm transition-all group"
          >
            <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0" style={{ background: bg }}>
              <Icon size={15} style={{ color }} />
            </div>
            <span className="text-slate-700 text-[13px] font-medium group-hover:text-slate-900 transition-colors">{label}</span>
          </Link>
        ))}
      </div>
    </Card>
  )
}

export default function BottomSection() {
  return (
    <div className="grid grid-cols-12 gap-5">
      <div className="col-span-4"><RecentActivity /></div>
      <div className="col-span-3"><PhaseSummary /></div>
      <div className="col-span-2"><PendingWork /></div>
      <div className="col-span-2"><Notifications /></div>
      <div className="col-span-1"><QuickActions /></div>
    </div>
  )
}
